<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangho Lee">
<meta name="dcterms.date" content="2024-04-30">

<title>Poisson Regression Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw2_questions_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw2_questions_files/libs/quarto-html/quarto.js"></script>
<script src="hw2_questions_files/libs/quarto-html/popper.min.js"></script>
<script src="hw2_questions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw2_questions_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw2_questions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw2_questions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw2_questions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw2_questions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw2_questions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangho Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>I will begin by acquiring and examining the dataset that is available. I will proceed to load and inspect this data using both Python and R, equipping me to perform various tasks as necessary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reticulate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>blueprinty <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"blueprinty.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>blueprinty <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: right;">patents</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">age</th>
<th style="text-align: right;">iscustomer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Midwest</td>
<td style="text-align: right;">32.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">786</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Southwest</td>
<td style="text-align: right;">37.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">348</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Northwest</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">927</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">24.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">830</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Southwest</td>
<td style="text-align: right;">37.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1046</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">29.5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">709</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Southwest</td>
<td style="text-align: right;">27.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1291</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">20.5</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">967</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">25.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Midwest</td>
<td style="text-align: right;">29.5</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyrsm <span class="im">as</span> rsm</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>blueprinty <span class="op">=</span> pd.read_csv(<span class="st">"blueprinty.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br></p>
<p>Next, I will focus on comparing histograms and calculating the mean number of patents across different customer statuses. My aim is to observe any patterns or discrepancies that emerge from this comparison. By visualizing the distribution of patents with histograms, I will be able to gain insights into the skewness, modality, and spread of patent counts among customers.</p>
<p>In the subsequent analysis, attention should be directed towards:</p>
<ul>
<li>Constructing histograms for each category of customer status.</li>
<li>Computing the mean number of patents for each customer status.</li>
<li>Interpreting any noticeable trends or anomalies in the data.</li>
</ul>
<p>I expect to see some information about how customer status might influence patent activity.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create separate dataframes for Blueprinty customers and non-customers</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>customers <span class="op">=</span> blueprinty[blueprinty[<span class="st">"iscustomer"</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>non_customers <span class="op">=</span> blueprinty[blueprinty[<span class="st">"iscustomer"</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms with KDE to compare the distribution of patent counts</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">12</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>sns.histplot(customers[<span class="st">"patents"</span>], kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'b'</span>, label<span class="op">=</span><span class="st">'Customers'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>sns.histplot(non_customers[<span class="st">"patents"</span>], kde<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">'r'</span>, label<span class="op">=</span><span class="st">'Non-customers'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Patents"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Frequency"</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Histogram of Patents by Customer Status"</span>, fontsize<span class="op">=</span><span class="dv">22</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>plt.legend(fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>customers <span class="op">=</span> blueprinty[blueprinty[<span class="st">"iscustomer"</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>non_customers <span class="op">=</span> blueprinty[blueprinty[<span class="st">"iscustomer"</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean number of patents for customers and non-customers</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>mean_customers <span class="op">=</span> customers[<span class="st">"patents"</span>].mean()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>mean_non_customers <span class="op">=</span> non_customers[<span class="st">"patents"</span>].mean()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>mean_customers, mean_non_customers  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(4.091370558375634, 3.6231772831926325)</code></pre>
</div>
</div>
<p><br></p>
<p>Based on the histogram with density and the mean calculations, here’s what I observe:</p>
<section id="histogram-analysis" class="level5">
<h5 class="anchored" data-anchor-id="histogram-analysis">Histogram Analysis</h5>
<ul>
<li>Distribution Shape: The histogram shows that non-customers (in red) have a broader distribution, with the highest frequency between 2 and 5 patents. This group has a longer tail, extending up to 15 patents.</li>
<li>Density: Customers (in blue) have a narrower distribution, with the peak density around 4 to 6 patents. This group has a lower overall frequency, suggesting fewer firms, but with a more concentrated range.</li>
<li>Comparative Observation: Although non-customers have a broader distribution and more frequency in the lower range, customers tend to cluster in the mid-patent range, suggesting they may achieve higher patent counts on average.</li>
</ul>
</section>
<section id="means" class="level5">
<h5 class="anchored" data-anchor-id="means">Means</h5>
<ul>
<li>Mean Values: The mean patent count for customers is 4.09, while for non-customers, it’s 3.62.</li>
<li>Interpretation: The higher mean for customers indicates that firms using Blueprinty’s software tend to achieve more patents on average.</li>
</ul>
</section>
<section id="overall" class="level5">
<h5 class="anchored" data-anchor-id="overall">Overall</h5>
<p>The data suggest that Blueprinty customers generally have a higher average patent count, with a tighter distribution around the 4-6 range. In contrast, non-customers display a broader distribution with a more substantial presence in the lower patent count range, but also a longer tail. This observation implies that using Blueprinty’s software might correlate with achieving more patents on average. Further analysis could determine the statistical significance and factors contributing to these differences.</p>
<p><br><br></p>
<p>Now, I will compare the distribution of Blueprinty’s customers across different regions, and their ages. I will find that certain regions have a higher concentration of customers, and there are specific age groups that are likely to be more prominent within our customer base. These patterns will suggest opportunities for targeted marketing campaigns and tailored service offerings based on regional and demographic trends.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Proportions of firms in each region by customer status</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>region_customer <span class="op">=</span> customers[<span class="st">"region"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>region_non_customer <span class="op">=</span> non_customers[<span class="st">"region"</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for age by customer status</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>age_customer <span class="op">=</span> customers[<span class="st">"age"</span>].describe()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>age_non_customer <span class="op">=</span> non_customers[<span class="st">"age"</span>].describe()</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>(region_customer, region_non_customer), (age_customer, age_non_customer) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>((region
Northeast    0.573604
Southwest    0.157360
South        0.101523
Midwest      0.086294
Northwest    0.081218
Name: proportion, dtype: float64, region
Northeast    0.374520
Southwest    0.204144
Midwest      0.158864
Northwest    0.131236
South        0.131236
Name: proportion, dtype: float64), (count    197.000000
mean      24.149746
std        7.565474
min       10.000000
25%       18.500000
50%       23.000000
75%       29.500000
max       46.500000
Name: age, dtype: float64, count    1303.000000
mean       26.691481
std         7.136209
min         9.000000
25%        21.500000
50%        26.500000
75%        32.000000
max        49.000000
Name: age, dtype: float64))</code></pre>
</div>
</div>
</section>
<section id="regional-distribution" class="level4">
<h4 class="anchored" data-anchor-id="regional-distribution">Regional Distribution</h4>
<ul>
<li>Customers: A significant proportion of Blueprinty’s customers are located in the Northeast (57.36%), followed by the Southwest (15.74%), South (10.15%), Midwest (8.63%), and Northwest (8.12%). This suggests that the Northeast region has a particularly high concentration of Blueprinty’s customer base.</li>
<li>Non-Customers: The regional distribution for non-customers is more evenly spread. The Northeast still leads (37.45%) but by a smaller margin compared to customers. The Southwest (20.41%), Midwest (15.89%), Northwest (13.12%), and South (13.12%) have a relatively more balanced distribution among non-customers.</li>
</ul>
</section>
<section id="age-distribution" class="level4">
<h4 class="anchored" data-anchor-id="age-distribution">Age Distribution</h4>
<ul>
<li>Customers: The average age of Blueprinty’s customer firms is 24.15 years, with a standard deviation of 7.56 years. The age range of customer firms spans from 10 to 46.5 years, with half of the customer base being 23 years old or younger. Non-Customers: Non-customer firms have a slightly higher average age of 26.69 years and a standard deviation of 7.14 years, ranging from 9 to 49 years. The median age is 26.5 years, indicating that non-customer firms are generally older than customer firms.</li>
</ul>
</section>
<section id="interpretation-and-marketing-implications" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-marketing-implications">Interpretation and Marketing Implications</h4>
<ul>
<li>The Northeast is a key region for Blueprinty’s customers, indicating a strong market presence or a higher demand for their software in this area. This could suggest potential for further market penetration or consolidation in the Northeast.</li>
<li>The more balanced regional distribution of non-customers suggests there may be untapped potential in regions outside the Northeast, particularly in the Southwest and Midwest. The age distribution shows that Blueprinty’s customers tend to be slightly younger firms. This could imply that younger firms are more open to adopting new software for patent applications or that Blueprinty’s offerings resonate more with such firms.</li>
<li>Non-customers being slightly older could indicate market opportunities: either these firms are loyal to other products or they are not aware of the potential benefits of Blueprinty’s software. This may point towards the need for outreach and education about Blueprinty’s offerings, targeting older firms.</li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
<p>Now, I’ll write the code for the likelihood or log-likelihood function of the Poisson model. This will help me analyze count data effectively, which is essential for the project’s statistical modeling. By understanding and implementing this function, I’ll be better equipped to handle data that inherently follows a Poisson distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>poisson_loglikelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, y) {</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  likelihood <span class="ot">&lt;-</span> <span class="sc">-</span>n<span class="sc">*</span>lambda <span class="sc">+</span> <span class="fu">sum</span>(y<span class="sc">*</span><span class="fu">log</span>(lambda)) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(likelihood)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I will use the function I developed to plot the parameter lambda on the horizontal axis against the likelihood or log-likelihood values on the vertical axis. I’ll vary lambda over a range and use the observed number of patents as the input value for Y. This visual representation will help me understand how the likelihood changes with different lambda values, aiding in selecting the most appropriate lambda for our model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> blueprinty<span class="sc">$</span>patents </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a sequence of lambda values</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>lambda_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>) </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for each lambda</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="ot">&lt;-</span> <span class="fu">sapply</span>(lambda_values, <span class="cf">function</span>(l) <span class="fu">poisson_loglikelihood</span>(l, y))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the log-likelihood against lambda</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">lambda =</span> lambda_values, <span class="at">log_likelihood =</span> log_likelihoods)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_to_plot, <span class="fu">aes</span>(<span class="at">x =</span> lambda, <span class="at">y =</span> log_likelihood)) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Log-Likelihood of Poisson Model"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lambda (\u03BB)"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log-Likelihood"</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="plot-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="plot-interpretation">Plot Interpretation</h4>
<ul>
<li><p>Shape of the Curve: The curve is unimodal, displaying a clear peak where the log-likelihood is maximized. This peak corresponds to the value of 𝜆 that best fits the observed patent count data (in terms of maximizing the likelihood).</p></li>
<li><p>Maximum Likelihood Estimate: The 𝜆 value at the peak of the curve is the Maximum Likelihood Estimate (MLE) for the Poisson model’s parameter. This value of 𝜆 is where the slope of the curve is zero (the first derivative of the log-likelihood equals zero).</p></li>
<li><p>Interpretation of 𝜆: In the context of the Poisson distribution 𝜆 represents the average number of events (patent awards in this case) occurring in a fixed interval of time or space. The plot suggests that the MLE of 𝜆 is somewhere around 3, though the exact value isn’t clear from the plot and would need to be found using the optim() function or by examining the computed log-likelihoods.</p></li>
<li><p>Goodness of Fit: The width of the curve around the peak can give us an intuition about the precision of the estimate; a narrower peak would indicate a more precise estimate of 𝜆. However, to truly assess the goodness of fit, we would need to look at more than just the log-likelihood function, including other diagnostics such as residuals and goodness-of-fit tests.</p></li>
<li><p>Usefulness: The log-likelihood plot is useful in optimization as it confirms that there is a maximum point that can be reached by adjusting 𝜆, which is what the optim() function in R would seek to find.</p></li>
</ul>
<p>I will now proceed to find the maximum likelihood estimate (MLE) by optimizing the likelihood function. I’ll use the optim() function in R to perform this optimization. This will help identify the parameter values that make the observed data most probable under the assumed statistical model, ensuring the best fit for our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the negative log-likelihood function for the Poisson distribution</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>neg_log_likelihood_poisson <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, y) {</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (lambda <span class="sc">&lt;=</span> <span class="dv">0</span>) {</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">Inf</span>)  <span class="co"># Return a large number to avoid log of non-positive numbers</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  likelihood <span class="ot">&lt;-</span> n <span class="sc">*</span> lambda <span class="sc">-</span> <span class="fu">sum</span>(y <span class="sc">*</span> <span class="fu">log</span>(lambda)) <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(likelihood)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'y' is your vector of observed patent counts</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> blueprinty<span class="sc">$</span>patents  </span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Use optim() to minimize the negative log-likelihood</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Starting value for lambda is chosen as the mean of y, which is a reasonable initial guess</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">mean</span>(y), <span class="at">fn =</span> neg_log_likelihood_poisson, <span class="at">y =</span> y, <span class="at">method =</span> <span class="st">"BFGS"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The MLE of lambda</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>lambda_mle <span class="ot">&lt;-</span> result<span class="sc">$</span>par</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the MLE of lambda</span></span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>lambda_mle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.684667</code></pre>
</div>
</div>
<p>The output of 3.684667 from the optim() function represents the maximum likelihood estimate (MLE) for the parameter𝜆 of the Poisson distribution, which models the number of patents awarded to each engineering firm over the last 5 years.</p>
<ul>
<li><p>Mean Rate (𝜆): The MLE 𝜆 of 3.684667 suggests that, under the Poisson model, the average number of patents awarded per firm over the specified period is approximately 3.68.</p></li>
<li><p>Model Assumption: This estimation is based on the assumption that the number of patents awarded follows a Poisson distribution, where each count is independent of others and occurs with a constant mean rate.</p></li>
<li><p>Data Fit: The estimated 𝜆 is the value that makes the observed data most probable under the Poisson model, meaning that it provides the best fit to the data according to the likelihood principle.</p></li>
<li><p>In practical terms, this MLE can be used as an estimate for predicting the expected number of patents for a similar firm, assuming that no other information (like firm age, region, or customer status) is considered. It also serves as a baseline measure for comparisons in more complex models that include additional covariates.</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
<p>Next, I’ll enhance the flexibility and accuracy of our likelihood or log-likelihood function by including an additional argument to accommodate a covariate matrix, X. I will also adjust the model’s parameter from a single lambda to a beta vector. To ensure that lambda remains positive, as required, I’ll employ the exponential function as the inverse link function. Thus, we define lambda for each observation as <span class="math inline">\(\lambda_i = e^{X_i' \beta}\)</span>. This modification allows us to model the influence of multiple covariates on our response variable, enhancing the robustness and relevance of our statistical analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>poisson_regression_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, Y, X) {</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(X <span class="sc">%*%</span> beta)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  log_likelihood <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">sum</span>(lambda) <span class="sc">+</span> <span class="fu">sum</span>(Y <span class="sc">*</span> <span class="fu">log</span>(lambda)) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(Y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="sc">-</span>log_likelihood)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I will now utilize the updated likelihood or log-likelihood function, incorporating the covariate matrix X, to perform parameter estimation using R’s optim(). The matrix X will be structured with its first column as all 1’s to include a constant term in the model. Subsequent columns will include age, age squared, binary variables representing regions (excluding one to avoid multicollinearity), and a binary variable for customer status.</p>
<p>After determining the maximum likelihood estimate (MLE) vector, I’ll use the Hessian matrix, returned by the optimization function, to calculate the standard errors of the beta parameter estimates. Finally, I will compile and present the results in a table format, showing both the coefficients and their corresponding standard errors. This approach will provide a comprehensive statistical basis for our model, ensuring precise interpretation and robust decision-making.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Prepare the Data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>blueprinty<span class="sc">$</span>age_squared <span class="ot">&lt;-</span> blueprinty<span class="sc">$</span>age<span class="sc">^</span><span class="dv">2</span>  </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>blueprinty<span class="sc">$</span>region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(blueprinty<span class="sc">$</span>region)  </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a model matrix including intercept, age, age squared, region, and iscustomer</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Dropping one region level to avoid dummy variable trap (reference category)</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> age <span class="sc">+</span> age_squared <span class="sc">+</span> region <span class="sc">+</span> iscustomer, <span class="at">data =</span> blueprinty)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> blueprinty<span class="sc">$</span>patents</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="do">### Find the MlE using optim()</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial beta estimates</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(X))</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> initial_beta, <span class="at">fn =</span> poisson_regression_likelihood, <span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>beta_mle <span class="ot">&lt;-</span> result<span class="sc">$</span>par</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="do">### Compute Standard Errors Using the Hessian</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>hessian_matrix <span class="ot">&lt;-</span> result<span class="sc">$</span>hessian</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the covariance matrix by inverting the Hessian</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>covariance_matrix <span class="ot">&lt;-</span> <span class="fu">solve</span>(hessian_matrix)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard errors are the square roots of the diagonal elements of the covariance matrix</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>std_errors <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(covariance_matrix))</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of coefficients and their standard errors</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>coef_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Estimate =</span> beta_mle, <span class="at">Std_Error =</span> std_errors)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(coef_table) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(X)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the table</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(coef_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Estimate    Std_Error
(Intercept)     -0.200877216 1.133793e-01
age              0.118687957 6.397346e-03
age_squared     -0.002249528 7.717834e-05
regionNortheast  0.020666023 4.198319e-02
regionNorthwest -0.011589573 5.310425e-02
regionSouth     -0.081466396 5.403375e-02
regionSouthwest  0.049380915 4.677724e-02
iscustomer       0.054200580 4.079591e-02</code></pre>
</div>
</div>
<p>This lists the estimated coefficients from a Poisson regression model and their respective standard errors:</p>
<ul>
<li><p>Intercept (Constant term): The estimate is -0.2009 with a standard error of 0.1134. Since the Poisson model is multiplicative due to the log link function, the interpretation is not straightforward. However, this term represents the log count of patents when all other covariates are zero (which isn’t necessarily a realistic scenario since age and age squared cannot be zero simultaneously).</p></li>
<li><p>Age: The coefficient for age is 0.1187 with a standard error of 0.0064. This suggests that, holding all other variables constant, a one-year increase in the age of a firm is associated with an 11.87% increase in the expected log count of patents awarded.</p></li>
<li><p>Age Squared: The age_squared term has a coefficient of -0.0022 with a standard error of 0.000077. The negative sign indicates that the relationship between age and patent count is not linear but rather parabolic, with a decreasing effect on patent count as age increases. This could suggest a peak age for firms at which the number of patents is maximized before it starts to decline.</p></li>
<li><p>Region: The region coefficients compare each region to the base category, which is omitted to avoid multicollinearity (commonly the first alphabetical region). For instance, being in the Northeast is associated with an increase in the expected log count of patents by 0.0207 compared to the base region, but this is not statistically significant given the relatively large standard error.</p></li>
<li><p>Is Customer: The coefficient for iscustomer is 0.0542 with a standard error of 0.0408. This implies that, all else being equal, firms that are customers of Blueprinty are expected to have a 5.42% increase in the log count of patents. The positive coefficient indicates a beneficial effect of using Blueprinty’s software, but given the standard error, this result may not be statistically significant. To determine significance, one would typically look at the z-score (Estimate divided by Std_Error) and the corresponding p-value.</p></li>
<li><p>In summary, the model suggests that the age of a firm and its squared term are important factors in predicting the success rate of patent awards, indicating a non-linear relationship. The coefficients for region suggest some regional effects, but the significance of these effects cannot be determined without additional statistics (such as p-values). Finally, being a Blueprinty customer appears to be associated with a higher expected count of patent awards, though without the p-values, we cannot confidently claim statistical significance.</p></li>
</ul>
<p><br></p>
<p>Next, I will validate the estimates obtained from the custom optimization by using R’s glm() function to fit the same Poisson model with our covariate matrix X. This step will serve as a robustness check, allowing us to compare the results from our manual optimization approach to those derived from established GLM methods. This comparison helps ensure our model’s reliability and accuracy in predicting outcomes based on our data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Poisson regression model using glm()</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>poisson_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(patents <span class="sc">~</span> age <span class="sc">+</span> <span class="fu">I</span>(age<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> region <span class="sc">+</span> iscustomer, <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>), <span class="at">data =</span> blueprinty)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poisson_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = patents ~ age + I(age^2) + region + iscustomer, 
    family = poisson(link = "log"), data = blueprinty)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -0.4512823  0.1836301  -2.458  0.01399 *  
age              0.1445364  0.0138793  10.414  &lt; 2e-16 ***
I(age^2)        -0.0028681  0.0002577 -11.131  &lt; 2e-16 ***
regionNortheast  0.0985960  0.0420070   2.347  0.01892 *  
regionNorthwest -0.0200942  0.0537833  -0.374  0.70869    
regionSouth      0.0571720  0.0526757   1.085  0.27776    
regionSouthwest  0.0513470  0.0472124   1.088  0.27678    
iscustomer       0.1181144  0.0389204   3.035  0.00241 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2362.5  on 1499  degrees of freedom
Residual deviance: 2178.8  on 1492  degrees of freedom
AIC: 6567.7

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<section id="model-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="model-coefficients">Model Coefficients</h4>
<ul>
<li><p>Intercept: The estimated intercept is -0.4513 with a standard error of 0.1836. It is statistically significant (p &lt; 0.05), indicating that the base rate of patents (when all other predictors are zero) is significantly different from zero. The negative sign suggests a lower base rate of patent awards.</p></li>
<li><p>Age: The coefficient for age is 0.1445 with a standard error of 0.0139. It is highly significant (p &lt; 2e-16), suggesting that as the age of a firm increases, the log count of patents typically increases. This implies a positive relationship between age and the number of patents, with each additional year increasing the expected log count of patents by 0.1445.</p></li>
<li><p>Age Squared (I(age^2)): The coefficient for age squared is -0.0029 with a standard error of 0.0003. It is also highly significant (p &lt; 2e-16), indicating a quadratic relationship between age and patents. The negative coefficient suggests that the effect of age on the number of patents diminishes as age increases, pointing to a peak effect after which additional years reduce the log count of patents.</p></li>
<li><p>Region: The coefficients for regions are measured relative to a baseline (omitted region). The Northeast region has a positive and significant coefficient (0.0986, p &lt; 0.05), indicating that firms in the Northeast tend to have a higher log count of patents compared to the baseline region. The coefficients for the Northwest, South, and Southwest are not statistically significant, suggesting no clear differences from the baseline region in those areas.</p></li>
<li><p>Is Customer (iscustomer): The coefficient for whether a firm is a customer of Blueprinty is 0.1181 with a standard error of 0.0389. It is significant (p &lt; 0.01), indicating that firms using Blueprinty’s software have a higher log count of patents compared to non-users, after controlling for other factors.</p></li>
</ul>
</section>
<section id="model-fit" class="level4">
<h4 class="anchored" data-anchor-id="model-fit">Model Fit</h4>
<ul>
<li><p>Null Deviance and Residual Deviance: These metrics indicate the goodness of fit of the model. The null deviance shows the deviance of a model with only the intercept, while the residual deviance shows the deviance of the model with all predictors. The reduction in deviance suggests that the model with predictors provides a better fit than the null model.</p></li>
<li><p>AIC: The Akaike Information Criterion for the model is 6567.7, which helps in model selection among different models. Lower AIC values generally indicate a better model.</p></li>
<li><p>Fisher Scoring iterations: The number of iterations taken to converge. A small number (5 in this case) typically indicates that the model converged successfully.</p></li>
</ul>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion</h4>
<ul>
<li>The model indicates that age, region (specifically Northeast), and usage of Blueprinty’s software are significant predictors of the number of patents awarded. The age effect is nonlinear, with both positive linear and negative quadratic components. The positive coefficient for Blueprinty’s software suggests that it effectively helps firms increase their patent counts. This could be used to argue that Blueprinty’s software enhances patent success, validating the software’s effectiveness for its users.</li>
</ul>
<p><br></p>
<section id="the-results-from-the-poisson-regression-analysis-provide-valuable-insights-into-the-effect-of-blueprintys-software-on-patent-success.-here-are-the-key-findings-and-their-interpretations" class="level5">
<h5 class="anchored" data-anchor-id="the-results-from-the-poisson-regression-analysis-provide-valuable-insights-into-the-effect-of-blueprintys-software-on-patent-success.-here-are-the-key-findings-and-their-interpretations">The results from the Poisson regression analysis provide valuable insights into the effect of Blueprinty’s software on patent success. Here are the key findings and their interpretations:</h5>
</section>
</section>
<section id="effect-of-blueprintys-software-on-patent-success" class="level4">
<h4 class="anchored" data-anchor-id="effect-of-blueprintys-software-on-patent-success">Effect of Blueprinty’s Software on Patent Success</h4>
<ul>
<li>Coefficient for iscustomer: The coefficient for the iscustomer variable, which indicates whether a firm uses Blueprinty’s software, is approximately 0.1181 with a standard error of 0.0389. This coefficient is statistically significant (p = 0.00241), which suggests a strong evidence of the association between using Blueprinty’s software and the number of patents obtained.</li>
</ul>
</section>
<section id="statistical-significance-and-practical-implications" class="level4">
<h4 class="anchored" data-anchor-id="statistical-significance-and-practical-implications">Statistical Significance and Practical Implications</h4>
<ul>
<li><p>Significance: The p-value associated with the iscustomer coefficient is well below the conventional threshold of 0.05, indicating that the results are statistically significant. This implies that the likelihood of observing such a coefficient by chance (if there were no real effect) is very low.</p></li>
<li><p>Magnitude of Effect: The coefficient of 0.1181 for iscustomer implies that, all else being equal, firms using Blueprinty’s software are expected to have a log-count of patents that is 0.1181 units higher than firms that do not use the software. Given that the model uses a log link, this translates into a multiplicative effect on the patent count. Specifically, the expected count of patents for customers of Blueprinty is exp(0.1181) times that of non-customers, which is about a 12.5% increase in the number of patents.</p></li>
</ul>
</section>
<section id="broader-implications" class="level4">
<h4 class="anchored" data-anchor-id="broader-implications">Broader Implications</h4>
<ul>
<li><p>Promotional Point: Blueprinty can use these results as a strong point in marketing and promotional materials, showcasing the statistically significant positive impact of their software on increasing patent counts among its users.</p></li>
<li><p>Strategic Decision Making: The clear positive effect of Blueprinty’s software on patent success could guide strategic decisions regarding product development, customer engagement, and market expansion strategies.</p></li>
<li><p>Customer Retention and Acquisition: Demonstrating quantifiable benefits, as revealed by this analysis, can aid in both retaining existing customers and acquiring new ones by providing empirical evidence of the software’s value.</p></li>
</ul>
</section>
<section id="conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="conclusion-1">Conclusion</h4>
<ul>
<li>In conclusion, the analysis strongly suggests that Blueprinty’s software has a positive effect on patent success. Firms using the software are likely to achieve a higher number of patents than those that do not, providing a quantifiable benefit of adopting Blueprinty’s technology. This effect is robust across statistical controls for other factors like age and regional location of the firms.</li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>